[llm]
base_url = "http://127.0.0.1:8080/v1" 
model = "numind/NuExtract-2.0-4B-GGUF" 
use_grammar = true 
max_tokens = 256
temperature = 0.0

[pdf]
path = "data/dys064.pdf" # pad naar test-paper (PDF)
max_pages = 20 # om sneller te testen

[task]
name = "total_inclusions" # testtaak

[logging]
level = "INFO"